/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DivulgaTudo;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natália Santos
 */
public class CadastroDeAnuncios extends javax.swing.JFrame {

    /**
     * Creates new form Capgemini
     */
    
    ArrayList<Anúncio> clientlist;
    
    public void LoadTableClient(){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"Cliente", "Anúncio", "Data de início", "Data de término", "Investimento/Dia"},0);
        
        for(int i=0;i<clientlist.size();i++){
           Object linha [] = new Object [] {clientlist.get(i).getClient_name(),
                                            clientlist.get(i).getAnnounc_name(),
                                            clientlist.get(i).getDatein(),
                                            clientlist.get(i).getDateout(),
                                            clientlist.get(i).getInvestperday()};
            modelo.addRow(linha);
        }
        
        table_cadastro.setModel(modelo);
    }
            
    public CadastroDeAnuncios() {
        initComponents();
        setLocationRelativeTo(null);
        ArrayList clientlist = new ArrayList ();
        btn_cadastro_save.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_cadastro = new javax.swing.JTable();
        l_cliente = new javax.swing.JLabel();
        l_anuncio = new javax.swing.JLabel();
        l_datein = new javax.swing.JLabel();
        l_dateout = new javax.swing.JLabel();
        l_investperday = new javax.swing.JLabel();
        c_cadastro_cliente = new javax.swing.JTextField();
        c_cadastro_anuncio = new javax.swing.JTextField();
        c_cadastro_datein = new javax.swing.JTextField();
        c_cadastro_dateout = new javax.swing.JTextField();
        c_cadastro_investperday = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_cadastro_new = new javax.swing.JButton();
        btn_cadastro_edit = new javax.swing.JButton();
        btn_cadastro_delete = new javax.swing.JButton();
        btn_cadastro_save = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        l_relatorio_anuncio = new javax.swing.JLabel();
        box_relatorio_cliente = new javax.swing.JComboBox<>();
        l_relatorio_totalvalue = new javax.swing.JLabel();
        l_relatorio_maxview = new javax.swing.JLabel();
        l_relatorio_maxclic = new javax.swing.JLabel();
        l_relatorio_maxshare = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        l_relatorio_cliente = new javax.swing.JLabel();
        box_relatorio_anuncio = new javax.swing.JComboBox<>();
        l_relatorio_time = new javax.swing.JLabel();
        box_relatorio_time = new javax.swing.JComboBox<>();
        c_relatorio_totalvalue = new javax.swing.JTextField();
        c_relatorio_maxview = new javax.swing.JTextField();
        c_relatorio_maxclic = new javax.swing.JTextField();
        c_relatorio_maxshare = new javax.swing.JTextField();
        l_relatorio_relatorio = new javax.swing.JLabel();
        l_filtro = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        l_relatorio_selecao = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_cadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Anúncio", "Data de início", "Data de término", "Investimento/Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_cadastro);

        l_cliente.setText("Nome do cliente:");

        l_anuncio.setText("Nome do anúncio:");

        l_datein.setText("Data de início:");

        l_dateout.setText("Data de término:");

        l_investperday.setText("Investimento por dia:");

        c_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cadastro_clienteActionPerformed(evt);
            }
        });

        c_cadastro_anuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cadastro_anuncioActionPerformed(evt);
            }
        });

        c_cadastro_datein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cadastro_dateinActionPerformed(evt);
            }
        });

        btn_cadastro_new.setText("Novo");
        btn_cadastro_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_newActionPerformed(evt);
            }
        });

        btn_cadastro_edit.setText("Editar");
        btn_cadastro_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_editActionPerformed(evt);
            }
        });

        btn_cadastro_delete.setText("Excluir");

        btn_cadastro_save.setText("Salvar");
        btn_cadastro_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cadastro_anuncio)
                            .addComponent(c_cadastro_cliente)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_investperday, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(l_datein)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cadastro_investperday, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c_cadastro_datein, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_dateout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_cadastro_dateout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cadastro_new, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastro_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cadastro_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cadastro_save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastro_new)
                    .addComponent(btn_cadastro_edit)
                    .addComponent(btn_cadastro_delete))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_cliente)
                    .addComponent(c_cadastro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_anuncio)
                    .addComponent(c_cadastro_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_datein)
                    .addComponent(c_cadastro_datein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_cadastro_dateout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_dateout))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_investperday)
                    .addComponent(c_cadastro_investperday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btn_cadastro_save)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        l_relatorio_anuncio.setText("Anúncio:");

        box_relatorio_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_relatorio_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_relatorio_clienteActionPerformed(evt);
            }
        });

        l_relatorio_totalvalue.setText("Valor total investido:");

        l_relatorio_maxview.setText("Quantidade máxima de visualizações:");

        l_relatorio_maxclic.setText("Quantidade máxima de cliques:");

        l_relatorio_maxshare.setText("Quantidade máxima de compartilhamentos:");

        l_relatorio_cliente.setText("Cliente:");

        box_relatorio_anuncio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        l_relatorio_time.setText("Intervalo de tempo:");

        box_relatorio_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        c_relatorio_totalvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_relatorio_totalvalueActionPerformed(evt);
            }
        });

        l_relatorio_relatorio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        l_relatorio_relatorio.setText("Relatório");

        l_filtro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        l_filtro.setText("Filtrar por:");

        l_relatorio_selecao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        l_relatorio_selecao.setText("Selecione o anúncio de interesse:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_relatorio_maxshare)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_relatorio_maxshare, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_relatorio_maxclic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_relatorio_maxclic))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_relatorio_maxview)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c_relatorio_maxview))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_relatorio_totalvalue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_relatorio_totalvalue)))
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l_relatorio_cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box_relatorio_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_relatorio_time)
                                .addGap(18, 18, 18)))
                        .addComponent(box_relatorio_time, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_relatorio_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_filtro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l_relatorio_anuncio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_relatorio_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l_relatorio_selecao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(l_relatorio_selecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_relatorio_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_relatorio_anuncio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(l_filtro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_relatorio_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_relatorio_time, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_relatorio_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_relatorio_cliente))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(l_relatorio_relatorio)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_relatorio_totalvalue)
                    .addComponent(c_relatorio_totalvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_relatorio_maxview)
                    .addComponent(c_relatorio_maxview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_relatorio_maxclic)
                    .addComponent(c_relatorio_maxclic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_relatorio_maxshare)
                    .addComponent(c_relatorio_maxshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cadastro_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cadastro_clienteActionPerformed

    private void c_cadastro_anuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cadastro_anuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cadastro_anuncioActionPerformed

    private void c_cadastro_dateinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cadastro_dateinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cadastro_dateinActionPerformed

    private void c_relatorio_totalvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_relatorio_totalvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_relatorio_totalvalueActionPerformed

    private void box_relatorio_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_relatorio_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_relatorio_clienteActionPerformed

    private void btn_cadastro_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastro_editActionPerformed

    private void btn_cadastro_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_saveActionPerformed
        //Date datein = date.parseDate(c_cadastro_datein.getText());
        //Date dateout = date.parseDate(c_cadastro_dateout.getText());
        //double investperday = Integer.parseDouble(c_cadastro_investperday.getText());
        // valeu a tentativa hehe
        Anúncio A = new Anúncio(c_cadastro_cliente.getText(),
                                c_cadastro_anuncio.getText());
                                //datein,
                                //dateout,
                                //investperday);
        
        clientlist.add(A);
        LoadTableClient();
        
    }//GEN-LAST:event_btn_cadastro_saveActionPerformed

    private void btn_cadastro_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_newActionPerformed
        c_cadastro_cliente.setText(" ");
        c_cadastro_anuncio.setText(" ");
        c_cadastro_datein.setText(" ");
        c_cadastro_dateout.setText(" ");
        c_cadastro_investperday.setText(" ");
        
        btn_cadastro_save.setEnabled((true));
        
    }//GEN-LAST:event_btn_cadastro_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeAnuncios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_relatorio_anuncio;
    private javax.swing.JComboBox<String> box_relatorio_cliente;
    private javax.swing.JComboBox<String> box_relatorio_time;
    private javax.swing.JButton btn_cadastro_delete;
    private javax.swing.JButton btn_cadastro_edit;
    private javax.swing.JButton btn_cadastro_new;
    private javax.swing.JButton btn_cadastro_save;
    private javax.swing.JTextField c_cadastro_anuncio;
    private javax.swing.JTextField c_cadastro_cliente;
    private javax.swing.JTextField c_cadastro_datein;
    private javax.swing.JTextField c_cadastro_dateout;
    private javax.swing.JTextField c_cadastro_investperday;
    private javax.swing.JTextField c_relatorio_maxclic;
    private javax.swing.JTextField c_relatorio_maxshare;
    private javax.swing.JTextField c_relatorio_maxview;
    private javax.swing.JTextField c_relatorio_totalvalue;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l_anuncio;
    private javax.swing.JLabel l_cliente;
    private javax.swing.JLabel l_datein;
    private javax.swing.JLabel l_dateout;
    private javax.swing.JLabel l_filtro;
    private javax.swing.JLabel l_investperday;
    private javax.swing.JLabel l_relatorio_anuncio;
    private javax.swing.JLabel l_relatorio_cliente;
    private javax.swing.JLabel l_relatorio_maxclic;
    private javax.swing.JLabel l_relatorio_maxshare;
    private javax.swing.JLabel l_relatorio_maxview;
    private javax.swing.JLabel l_relatorio_relatorio;
    private javax.swing.JLabel l_relatorio_selecao;
    private javax.swing.JLabel l_relatorio_time;
    private javax.swing.JLabel l_relatorio_totalvalue;
    private javax.swing.JTable table_cadastro;
    // End of variables declaration//GEN-END:variables
}
